apiVersion: v2
name: postgres-operator
description: Zalando Postgres Operator for Kubernetes
type: application
version: 1.0.0
appVersion: "1.12.2"

dependencies:
  - name: postgres-operator
    version: "1.12.2"
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
