{{- if .Values.cephObjectStore.enabled }}
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: {{ .Values.cephObjectStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  metadataPool:
    failureDomain: {{ .Values.cephObjectStore.metadataPool.failureDomain }}
    replicated:
      size: {{ .Values.cephObjectStore.metadataPool.replicated.size }}
  dataPool:
    failureDomain: {{ .Values.cephObjectStore.dataPool.failureDomain }}
    replicated:
      size: {{ .Values.cephObjectStore.dataPool.replicated.size }}
  preservePoolsOnDelete: {{ .Values.cephObjectStore.preservePoolsOnDelete }}
  gateway:
    port: {{ .Values.cephObjectStore.gateway.port }}
    instances: {{ .Values.cephObjectStore.gateway.instances }}
    {{- if .Values.cephObjectStore.gateway.securePort }}
    securePort: {{ .Values.cephObjectStore.gateway.securePort }}
    {{- end }}
    {{- if .Values.cephObjectStore.gateway.sslCertificateRef }}
    sslCertificateRef: {{ .Values.cephObjectStore.gateway.sslCertificateRef }}
    {{- end }}
    resources:
      {{- toYaml .Values.cephObjectStore.gateway.resources | nindent 6 }}
  {{- if .Values.cephObjectStore.security }}
  security:
    {{- toYaml .Values.cephObjectStore.security | nindent 4 }}
  {{- end }}
  {{- if .Values.cephObjectStore.protocols }}
  protocols:
    {{- toYaml .Values.cephObjectStore.protocols | nindent 4 }}
  {{- end }}
---
{{- if .Values.cephObjectStore.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cephObjectStore.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.cephObjectStore.service.type }}
  ports:
    - name: http
      port: {{ .Values.cephObjectStore.service.port }}
      targetPort: {{ .Values.cephObjectStore.service.targetPort }}
      {{- if .Values.cephObjectStore.service.nodePort }}
      nodePort: {{ .Values.cephObjectStore.service.nodePort }}
      {{- end }}
  selector:
    app: rook-ceph-rgw
    rook_object_store: {{ .Values.cephObjectStore.name }}
{{- end }}
{{- end }}
